LICENSE

WEBSITE

AZEN-COMPILER-OPEN-SOURCE-LICENSE

COPYRIGHT AZEN-COMPILER-OPEN-SOURCE-FOUNDATION

AZEN-COMPILER LICENSE IS COMPATIBLE WITH GPL-2. AZEN-COMPILER KERNEL
LICENSE RIGHTS ARE RESERVED FOR THE INDIVIDUALS SPECIFIED UNDER AZEN
COMPILER OPEN SOURCE FOUNDATION OR AZEN COMPILER. MODIFICATION OR
RECOMPILATION OF AZEN-COMPILER SOFTWARE IS POSSIBLE, BUT THE SOFTWARE
LICENSE SHOULD THEN BE DISTRIBUTED ONLY WITH AZEN-COMPILER LICENSE.
AZEN-COMPILER IS A SOFTWARE LICENSE THAT VALUES STABILIZATION, AND IF
USED FOR MALICIOUS PURPOSES, THE LICENSE IS NOT RESPONSIBLE FOR THE
SOFTWARE.

© A-ZEN-COMPILER-OPEN-SOURCE-FOUNDATION

© ZAMAN HUSEYINLI
