#include <stdio.h>
#include <deviceingmanager.h>

#ifdef DEVICEING-RADAR-FOUNDING-MODULE
#ifndef ARCH-DEVIECING-SUB-MODULE
#ifdef ARCH-SYS-ROOT-DEVICEING-FOUNDING-MODULE
#ifdef PROMPO-DEVICEING-NVIDIA-SPEEDRUNNER 
#ifdef SUB-MODULE-PROMPO-KERNEL
#undef  BOOTABLE-PROMPO-KERNEL-SYSTEM-MODULE
#ifndef SUB-DEVICEING-KERNEL-ACTIVATION
#undef DEVCE*CHANGER
#endif
