#include <stdio.h>
#include <iso-imager.h>


#ifdef ISO-IMAGER-READING-MODULES-FROMER
#ifndef SYS-ROOT-ISO-DEVICEING-CHANGER
#ifdef ISO-IMAGER-ZEN-FROMER
#undef SO-MAGER-NO-PUBLC-KERNEL-MODULE
#ifndef ISO-READING-KERNELFS-MODULES
#ifdef ISO-IMAGER-SYS-ROOT-KERNELFUNCTIONERS
#endif
